server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&allowPublicKeyRetrieval=TRUE&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "xxxxx"
#showSql
logging:
  level:
    #这个指定你的dao层，也就是mapper文件的所在包
    com.xuehua.wms.mapper: DEBUG,



